/* Generated By:JavaCC: Do not edit this line. CLParserTreeConstants.java Version 5.0 */
public interface CLParserTreeConstants
{
  public int JJTSTARTPROGRAM = 0;
  public int JJTVARIABLESBLOCK = 1;
  public int JJTCODEBLOCK = 2;
  public int JJTVARIABLEDECLARATION = 3;
  public int JJTSTATEMENT = 4;
  public int JJTEXPRESSION = 5;
  public int JJTTERM = 6;
  public int JJTFACTOR = 7;


  public String[] jjtNodeName = {
    "startProgram",
    "variablesBlock",
    "codeBlock",
    "variableDeclaration",
    "statement",
    "expression",
    "term",
    "factor",
  };
}
/* JavaCC - OriginalChecksum=5abaeb0aabf8e8c82f8648c02d06654d (do not edit this line) */
