/* Generated By:JJTree&JavaCC: Do not edit this line. CLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_PROGRAM = 5;
  /** RegularExpression Id. */
  int END_PROGRAM = 6;
  /** RegularExpression Id. */
  int VARIABLES = 7;
  /** RegularExpression Id. */
  int CODE = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int MULTIPLY = 18;
  /** RegularExpression Id. */
  int DIVIDE = 19;
  /** RegularExpression Id. */
  int LESS_THAN_EQUAL = 20;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUAL = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int NOT_EQUAL = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"startProgram\"",
    "\"endProgram\"",
    "\"variables:\"",
    "\"code:\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<FLOAT>",
    "<STRING>",
    "<CHAR>",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"<>\"",
  };

}
